= Bay Wei Heng - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets
:xrefstyle: short
:experimental:

== Overview

This Project Portfolio details my contributions to project EPIC, which demonstrates that I am capable of producing functional code,
and working in a team on a large project.

---

== PROJECT: EPIC

Event Planning isn’t Complicated (EPIC) is a desktop application used for *event planning
and registration for large organisations*. EPIC handles event attendance management with
simplicity and efficiency. By storing all of the contacts in a common database, the same person
can be registered for multiple events without having to re-enter his or her details for each event.
EPIC is optimized for event planners who prefer typing to using the mouse.

== Summary of contributions

* *Major Enhancement*: Implementation of event-person interactions
** Description: Persons can be registered for/deregistered from events, and a particular event's participants can be
displayed. These functions form the core of the application.
** Design Decisions: There were various design decisions I had to make through the course of implementing these interactions.
Two of the most notable ones are:
*** Editing of persons is done in a mutable manner.
*** Deletion of persons still registered for an event is not allowed.
** Justification: I made the above choices for the following reasons:
*** Mutable edit - Allows editing of persons to be done in an efficient manner; events automatically receive the edited participant's
data, without the need to duplicate the data and update each event manually.
*** Deletion constraint - Acts as a safeguard to ensure that every participant's data is present during event registration.
** Highlights: This enhancement was done across multiple components:
*** Modified the Model component to allow navigability from events to persons.
*** Added new commands to the Logic component, and provided their implementation.
*** Ensured that the UI component updates whenever a person is edited, even when it is done in a mutable manner, and similarly
when a person is registered for/deregistered from an event.

* *Minor Enhancement*: Overhaul of undo-redo functionality
** Previous Implementation: In the previous iteration of the product, the *entire* memory contents of the application were duplicated
and stored to facilitate undoing/redoing commands.
** Current Implementation: In EPIC v1.5, _every_ undoable command now learns how to undo/redo itself in the pre-processing
stage. This knowledge is stored alongside the command.
** Justification: The new implementation only requires essential, and hence minimal, information to be stored, *significantly
reducing memory consumption* of EPIC.

* *Code contributed*: [https://github.com/CS2103JAN2018-W13-B2/main/blob/master/collated/functional/bayweiheng.md[Functional code]] [https://github.com/CS2103JAN2018-W13-B2/main/blob/master/collated/test/bayweiheng.md[Test code]]

* *Other contributions*:

** Project management:
*** Set up team repository on GitHub
*** Set up continuous integration tools such as https://travis-ci.org/CS2103JAN2018-W13-B2/main[Travis CI] and https://ci.appveyor.com/project/bayweiheng/addressbook-level4-kqc9e[Appveyor]
*** Set up coverage checkers such as https://coveralls.io/github/CS2103T-2018-W13-B2[Coveralls]
*** Managed releases https://github.com/CS2103JAN2018-W13-B2/main/releases/tag/v1.2[v1.2], https://github.com/CS2103JAN2018-W13-B2/main/releases/tag/v1.3[v1.3],
and https://github.com/CS2103JAN2018-W13-B2/main/releases/tag/1.4[v1.4] on GitHub
** Documentation:
*** Editor for the user and developer guides, ensuring consistency and checking for language errors. Relevant PRs: https://github.com/CS2103JAN2018-W13-B2/main/pull/103[#103]
    and https://github.com/CS2103JAN2018-W13-B2/main/pull/147[#147]
*** Added various example outcomes for previous commands in the User Guide
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-W13-B2/main/pull/41[#41]
*** Posted bugs of teammates as issues on GitHub: https://github.com/CS2103JAN2018-W13-B2/main/issues/107[#107] and https://github.com/CS2103JAN2018-W13-B2/main/issues/155[#155]
*** Reported bugs and suggestions for other teams in the class. Relevant issues on GitHub:
https://github.com/CS2103JAN2018-T11-B2/main/issues/110[#110] (has follow-up with team),
https://github.com/CS2103JAN2018-T11-B2/main/issues/89[#89] (suggested fix),
https://github.com/CS2103JAN2018-T11-B2/main/issues/112[#112]

<<<

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

_Excerpts from How to Use the GUI_

include::../UserGuide.adoc[tag=uiinteractions]

_Excerpts from Undoing Commands_

include::../UserGuide.adoc[tag=undo]

_Excerpts from Redoing Commands_

include::../UserGuide.adoc[tag=redo]

_Excerpts from Registering a Person for an Event_

include::../UserGuide.adoc[tag=register]
<<<

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

_Excerpts from Edit Person/Event Features_

include::../DeveloperGuide.adoc[tag=editfeature]

_Excerpts from Undo/Redo Features_

include::../DeveloperGuide.adoc[tag=editedundoparts]

include::../DeveloperGuide.adoc[tag=undoredochanges]

_Excerpts from Register/Deregister Features_

include::../DeveloperGuide.adoc[tag=registerpersons]
