= Raynold Ng - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Event Planning isn’t Complicated (EPIC)

---

== Overview

Event Planning isn’t Complicated (EPIC) is a desktop application used for *event planning
and registration for large organisations*. EPIC handles event attendance management with
simplicity and efficiency. By storing all of the contacts in a common database, the same person
can be registered for multiple events without having to re-enter his or her details for each event.
EPIC is optimized for event planners who prefer typing to using the mouse.

== Summary of contributions

* *Major enhancement*: overhauled UI to a three panel system that displays all persons, events and attendees of selected
event in their respective panels.
** What it does: A three panel system displaying stored persons, events and attendees. It auto updates itself when there
are changes to data.
** Justification: This feature *enhances the user experience* tremendously as the user can view all three panels
without having to cycle between lists. Being able to view all three lists in a clean and intuitive interface empowers the user
to type out commands that require parameters from all three lists without breaking his workflow. As such commands are
the core functionailty of EPIC, it is imperative that UI is clean and user-friendly.

** Highlights: This enhancement leverages several patterns such as the Model View Controller (MVC) Pattern, Observer
Pattern and JavaFx Beans Convention to elegantly trigger UI updates upon data changes. Using such patterns made UI
updates *automatic and resource-efficient* The feature was implemented in a
modular fashion, which makes maintenance and testing easy.
* *Minor enhancement*: added the `find-attendance` command that filters the attendance panel and the `list-attendance`
command that resets it.

* *Code contributed*: [https://github.com/CS2103JAN2018-W13-B2/main/blob/master/collated/functional/raynoldng.md[Functional code]] [https://github.com/CS2103JAN2018-W13-B2/main/blob/master/collated/test/raynoldng.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases https://github.com/CS2103JAN2018-W13-B2/main/releases/tag/1.4.1[v.1.4.1]- https://github.com/CS2103JAN2018-W13-B2/main/releases/tag/v1.5rc[v.1.5rc]  on GitHub
** Enhancements to existing features:
*** Fixed failing test cases due to incorrect data (Pull requests https://github.com/CS2103JAN2018-W13-B2/main/pull/110[#110])
*** Wrote additional tests for existing features  (Pull requests https://github.com/CS2103JAN2018-W13-B2/main/pull/148[#148], https://github.com/CS2103JAN2018-W13-B2/main/pull/170[#170])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/CS2103JAN2018-W13-B2/main/pull/158[#158]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/CS2103JAN2018-W13-B2/main/pull/44[#44]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/CS2103JAN2018-W10-B3/main/issues/118#event-1562496445[1], https://github.com/CS2103JAN2018-W10-B3/main/issues/110#issuecomment-379736418[2])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=uilayout]

include::../UserGuide.adoc[tag=selectevent]

include::../UserGuide.adoc[tag=attendance-search]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=findregistrant]

include::../DeveloperGuide.adoc[tag=uicomponent]

include::../DeveloperGuide.adoc[tag=threepaneui]


